### ISSUE TITLE
Getting incorrect public keys?

### ISSUE THREAD

**Issue by brett-doffing** [pebble8888/secp256k1swift#1]
I may be doing something wrong in just trying this out, but when I run the following code:

`let context = secp256k1_context_create([SECP256K1_FLAGS.SECP256K1_CONTEXT_SIGN, SECP256K1_FLAGS.SECP256K1_CONTEXT_VERIFY])`

`let privateKey = "18E14A7B6A307F426A94F8114701E7C8E774E7F9A47E2C2035DB29A206321725".toUInt8`

`let boolVerified = secp256k1_ec_seckey_verify(context!, privateKey)`

`var pubkey = secp256k1_pubkey()`

`let boolPublicKey = secp256k1_ec_pubkey_create(context!, &pubkey, privateKey)`

`var serializedPubkey = [UInt8](repeating: 0, count:65)`

`var myInt = UInt(65)`

`let boolPubkeySerialized = secp256k1_ec_pubkey_serialize(context!, &serializedPubkey, &myInt, pubkey, [SECP256K1_FLAGS.SECP256K1_EC_UNCOMPRESSED])`

`let pubkeyParsed = secp256k1_ec_pubkey_parse(context!, &pubkey, serializedPubkey, UInt(serializedPubkey.count))`

`print(serializedPubkey.hexDescription())`

I get:

> 043ddd7031191ed8e24ec7e33d5025a07dbb3b3e40b7884d4ad7503b61c4282214af0aa8d06c1f98c3601e5b7236f9ac4e6f2c58c2120eb33ebc88001a570b0fcf

when I should get:

> 0450863AD64A87AE8A2FE83C1AF1A8403CB53F53E486D8511DAD8A04887E5B23522CD470243453A299FA9E77237716103ABC11A1DF38855ED6F2EE187E9C582BA6

Also, I tried:
`let privateKey = "11095327A9E4921336E93834D8A93395476FC3665B59668459F9AFC9A3917461".toUInt8`

and got:

> 04667f0bac738737bebbc8ba3bd279a1aad4e34fef75d6896388318328bf8b283447fe70abe3de5f352ca0525f834268a6ff5e90757a6d7f244c5b020bbe8caf02

when I should get:

> 0459DDBF24EE3D88CE431DAFB9F7A2B30CB5E5D811C4AE4347FA3C89FD1FCAFBAAF21F14907B8D98A069E673217DCAA10141090D3536090E689F13EF7C87DBCFAF

Am I doing something wrong, or is there an issue here?

**Comment by pebble8888** [comment]
Please try this. 

```swift
let privateKey = String("18E14A7B6A307F426A94F8114701E7C8E774E7F9A47E2C2035DB29A206321725".reversed()).toUInt8
```

**Comment by pebble8888** [comment]
Please try this.

```swift
let privateKey = "18E14A7B6A307F426A94F8114701E7C8E774E7F9A47E2C2035DB29A206321725".unhexlify()
```

**Comment by brett-doffing** [comment]
That did the trick.
